version: '3.7'

services:
  postgres_app:
    container_name: postgres_app
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sql_app
    volumes:
      - postgres-data-app:/var/lib/postgresql/data/

volumes:
  postgres-data-app:
